/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces.emergentes;

import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import serviciosBD.catalogo_servicio;

/**
 *
 * @author Soxtec Desarrollo
 */
public class requerimientos_detalle_ifz extends javax.swing.JDialog {

     boolean informacion=false;
     
     
    public requerimientos_detalle_ifz(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        
        catalogo_servicio catalogo=new catalogo_servicio();
        insumoTBL.setModel(catalogo.listaPorTipoCatalogoModel(19));;
        redimenciona1();
    }

    
    public void redimenciona1(){
        insumoTBL.getColumnModel().getColumn(0).setMaxWidth(0);
        insumoTBL.getColumnModel().getColumn(0).setMinWidth(0);
        insumoTBL.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        insumoTBL.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        insumoBuscarTXT = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        insumoTBL = new javax.swing.JTable();
        cantidadSPN = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        ObservacionesTXT = new javax.swing.JTextArea();
        precioTXT = new javax.swing.JTextField();
        importeTXT = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        InsumoTXT = new javax.swing.JTextField();
        insumoIdTXT = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agrega Concepto");

        jLabel1.setText("Insumo");

        jLabel2.setText("Cantidad");

        jLabel3.setText("Observaciones");

        jLabel4.setText("Precio Unitario");

        jLabel5.setText("Impoirte");

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        insumoBuscarTXT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                insumoBuscarTXTKeyReleased(evt);
            }
        });

        insumoTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        insumoTBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                insumoTBLMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(insumoTBL);

        cantidadSPN.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                change(evt);
            }
        });
        cantidadSPN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cantidadSPNMouseReleased(evt);
            }
        });
        cantidadSPN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cantidadSPNKeyReleased(evt);
            }
        });

        ObservacionesTXT.setColumns(20);
        ObservacionesTXT.setRows(5);
        jScrollPane2.setViewportView(ObservacionesTXT);

        precioTXT.setText("0");
        precioTXT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                precioTXTKeyReleased(evt);
            }
        });

        importeTXT.setEditable(false);
        importeTXT.setText("0");

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        InsumoTXT.setEditable(false);

        insumoIdTXT.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cantidadSPN)
                                .addGap(331, 331, 331))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(importeTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(precioTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 16, Short.MAX_VALUE)
                        .addComponent(insumoIdTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(insumoBuscarTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                                .addComponent(InsumoTXT)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(insumoBuscarTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InsumoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insumoIdTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cantidadSPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(precioTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(importeTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insumoBuscarTXTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_insumoBuscarTXTKeyReleased
        catalogo_servicio catalogo=new catalogo_servicio();
        insumoTBL.setModel(catalogo.listaPorTipoCatalogoModel(19,insumoBuscarTXT.getText()));;
        redimenciona1();
    }//GEN-LAST:event_insumoBuscarTXTKeyReleased

    private void insumoTBLMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insumoTBLMouseReleased
        
        if (insumoTBL.getSelectedRow()!=-1){
            InsumoTXT.setText(insumoTBL.getValueAt(insumoTBL.getSelectedRow(), 1)+"");
            insumoIdTXT.setText(insumoTBL.getValueAt(insumoTBL.getSelectedRow(), 0)+"");
        }
    }//GEN-LAST:event_insumoTBLMouseReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
       
        String mensaje="";
        boolean valido=true;
        
        
        if (insumoIdTXT.getText().equals("0")   ){
            valido=false;
            mensaje="Por favor selecciona un Insumo";
        }
        if ( cantidadSPN.getValue().equals("0") ){
            valido=false;
            mensaje="Por favor selecciona una cantidad distinta de 0";
        }
        if (precioTXT.getText().equals("0")   ){
            valido=false;
            mensaje="Por favor ingrese un precio";
        }
        if (importeTXT.getText().equals("0")   ){
            valido=false;
            mensaje="El importe debe ser mayor que 0";
        }
     
        
        if (valido){
            informacion=true;
            this.dispose();
            
        }
        else{
            JOptionPane.showMessageDialog(null, mensaje);
        }
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    public void calculaTotales(){
        
        float cantidad=Float.parseFloat(cantidadSPN.getValue()+"");
        float precio=Float.parseFloat(precioTXT.getText());
        
        
        importeTXT.setText((cantidad*precio)+"");
        
    }
    
    
    private void cantidadSPNKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadSPNKeyReleased
        
        
        calculaTotales();
        
        
        
    }//GEN-LAST:event_cantidadSPNKeyReleased

    private void precioTXTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precioTXTKeyReleased
        calculaTotales();
        
    }//GEN-LAST:event_precioTXTKeyReleased

    private void cantidadSPNMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cantidadSPNMouseReleased
        calculaTotales();
        
    }//GEN-LAST:event_cantidadSPNMouseReleased

    private void change(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_change
        calculaTotales();
    }//GEN-LAST:event_change

    public boolean isInformacion() {
        return informacion;
    }

    
    
    
    public JTextField getInsumoTXT() {
        return InsumoTXT;
    }

    public JTextArea getObservacionesTXT() {
        return ObservacionesTXT;
    }

    public JSpinner getCantidadSPN() {
        return cantidadSPN;
    }

    public JTextField getImporteTXT() {
        return importeTXT;
    }

    public JTextField getInsumoBuscarTXT() {
        return insumoBuscarTXT;
    }

    public JTextField getInsumoIdTXT() {
        return insumoIdTXT;
    }

    public JTable getInsumoTBL() {
        return insumoTBL;
    }

    public JTextField getPrecioTXT() {
        return precioTXT;
    }

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(requerimientos_detalle_ifz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(requerimientos_detalle_ifz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(requerimientos_detalle_ifz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(requerimientos_detalle_ifz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                requerimientos_detalle_ifz dialog = new requerimientos_detalle_ifz(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InsumoTXT;
    private javax.swing.JTextArea ObservacionesTXT;
    private javax.swing.JSpinner cantidadSPN;
    private javax.swing.JTextField importeTXT;
    private javax.swing.JTextField insumoBuscarTXT;
    private javax.swing.JTextField insumoIdTXT;
    private javax.swing.JTable insumoTBL;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField precioTXT;
    // End of variables declaration//GEN-END:variables
}
