/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import javax.swing.table.DefaultTableModel;
import serviciosBD.persona_servicio;
import utilidadesbasicas.utilidadJFrame;
import utilidadesbasicas.utilidadValidacionNulo;

/**
 *
 * @author Abraham
 */
public class empleados_ifz extends javax.swing.JFrame {

    DefaultTableModel TBLDTMempleados;
   
    utilidadesbasicas.utilidadValidacionNulo validacionNulos;
    utilidadesbasicas.utilidadJFrame agrupacion;
    
    public empleados_ifz() {
        
        
        persona_servicio empleado=new persona_servicio();
        TBLDTMempleados = empleado.LISTAempleados();
        initComponents();
        
        validacionNulos=new utilidadValidacionNulo();
        validacionNulos.add(TXTapellidoPaterno);
        validacionNulos.add(TXTapellidoMaterno); 
        validacionNulos.add(TXTnombres);
        
        agrupacion=new utilidadJFrame();
        agrupacion.add(TXTidEmpleado);
        agrupacion.add(TXTapellidoPaterno);
        agrupacion.add(TXTapellidoMaterno); 
        agrupacion.add(TXTnombres);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TBLEemplados = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TXTbuscaEmpleado = new javax.swing.JTextField();
        TXTidEmpleado = new javax.swing.JTextField();
        TXTapellidoPaterno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TXTapellidoMaterno = new javax.swing.JTextField();
        TXTnombres = new javax.swing.JTextField();
        BTNactualizar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TBLEemplados.setModel(TBLDTMempleados);
        TBLEemplados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TBLEempladosMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(TBLEemplados);

        jButton1.setText("Regresar <<");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Empleado");

        TXTbuscaEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TXTbuscaEmpleadoKeyReleased(evt);
            }
        });

        TXTidEmpleado.setEditable(false);

        jLabel2.setText("Numero Empleado");

        jLabel3.setText("Apellido Paterno");

        jLabel4.setText("Apellido Materno");

        jLabel5.setText("Nombres");

        BTNactualizar.setText("Agregar nuevo empleado");
        BTNactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNactualizarActionPerformed(evt);
            }
        });

        jButton3.setText("Limpiar campos");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TXTbuscaEmpleado))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(363, 363, 363)
                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(TXTapellidoPaterno))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TXTidEmpleado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTapellidoMaterno, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTnombres, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BTNactualizar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TXTbuscaEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTapellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTidEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TXTapellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TXTnombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 15, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(BTNactualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXTbuscaEmpleadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTbuscaEmpleadoKeyReleased
        persona_servicio empleado=new persona_servicio();
        TBLDTMempleados = empleado.LISTAempleados(TXTbuscaEmpleado.getText());
        TBLEemplados.setModel(TBLDTMempleados);
    }//GEN-LAST:event_TXTbuscaEmpleadoKeyReleased

    private void TBLEempladosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBLEempladosMouseReleased
        if (TBLEemplados.getSelectedRow()!=-1){
            persona_servicio empleado=new persona_servicio();
            empleado.setIdPersona(Integer.parseInt(TBLDTMempleados.getValueAt(TBLEemplados.getSelectedRow(), 1)+""));
            empleado.get();
            TXTidEmpleado.setText(empleado.getIdPersona()+"");
            TXTapellidoPaterno.setText(empleado.getApellidoPaterno());
            TXTapellidoMaterno.setText(empleado.getApellidoMaterno());
            TXTnombres.setText(empleado.getNombre());
            BTNactualizar.setText("Actualiza información de empleado");
            
        }
        
    }//GEN-LAST:event_TBLEempladosMouseReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            TXTidEmpleado.setText("");
            TXTapellidoPaterno.setText("");
            TXTapellidoMaterno.setText("");
            TXTnombres.setText("");
            BTNactualizar.setText("Agregar nuevo empleado");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void BTNactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNactualizarActionPerformed
        
        persona_servicio empleado=new persona_servicio();
        
        boolean insetado=false;
        
        if (TXTidEmpleado.getText().equals("")){  //Se inserta
            
            empleado.setApellidoPaterno(TXTapellidoPaterno.getText());
            empleado.setApellidoMaterno(TXTapellidoMaterno.getText());
            empleado.setNombre(TXTnombres.getText());
            empleado.setIdTipoPersona(2);
            
            insetado=empleado.add();
            
            if (insetado){
               agrupacion.limpiaTodosLosCampos();
                BTNactualizar.setText("Agregar nuevo empleado");
               
            }else{
                javax.swing.JOptionPane.showMessageDialog(null, "No pudo ser insetado el empleado");
            }
            
        }
        else{ //Se guarda
        
            empleado.setIdPersona(Integer.parseInt(TXTidEmpleado.getText()));
            empleado.setApellidoPaterno(TXTapellidoPaterno.getText());
            empleado.setApellidoMaterno(TXTapellidoMaterno.getText());
            empleado.setNombre(TXTnombres.getText());
            empleado.setIdTipoPersona(2);
            
            insetado=empleado.update();
            
            if (insetado){
               agrupacion.limpiaTodosLosCampos();
                BTNactualizar.setText("Agregar nuevo empleado");
            }else{
                javax.swing.JOptionPane.showMessageDialog(null, "No pudo ser actualizado el empleado");
            }
            
        }
        
       
       
        TBLDTMempleados = empleado.LISTAempleados();
        TBLEemplados.setModel(TBLDTMempleados);
        
        
        
    }//GEN-LAST:event_BTNactualizarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        menu_ifz V=new menu_ifz();
        V.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNactualizar;
    private javax.swing.JTable TBLEemplados;
    private javax.swing.JTextField TXTapellidoMaterno;
    private javax.swing.JTextField TXTapellidoPaterno;
    private javax.swing.JTextField TXTbuscaEmpleado;
    private javax.swing.JTextField TXTidEmpleado;
    private javax.swing.JTextField TXTnombres;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
