/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.StringTokenizer;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import serviciosBD.ManejadorDeDatos;
import serviciosBD.catalogo_servicio;
import serviciosBD.estado_servicio;
import utilidadesReportesJasper.Reportes;
import utilidadesbasicas.archivoProperties;

/**
 *
 * @author Soxtec Desarrollo
 */
public class reportesGerenciales_ifz extends javax.swing.JFrame {

    String estadosCombo[];
    
    
    
    public reportesGerenciales_ifz() {
        initComponents();
        
        
        catalogo_servicio catalogo=new catalogo_servicio();
        String Catalogo[][]= catalogo.listaPorTipoCatalogo(20);
        
        String CentrosDeCosto[]=new String[Catalogo.length];
        
        for(int i=0;i<Catalogo.length;i++){
            CentrosDeCosto[i]=Catalogo[i][1];
        }
        
        CMBcentroDeCostoINICIAL.setModel(new DefaultComboBoxModel(CentrosDeCosto)  );
        CMBcentroDeCostoFINAL.setModel(new DefaultComboBoxModel(CentrosDeCosto)  );
        CMBcentrosDeCostoEstadistico1.setModel(new DefaultComboBoxModel(CentrosDeCosto)  );
        CMBcentrosDeCostoEstadistico2.setModel(new DefaultComboBoxModel(CentrosDeCosto)  );
        
        estado_servicio estado=new estado_servicio();
        
        ArrayList<String> estadosOrdenCompra=new ArrayList();
        estadosOrdenCompra.add("1");
        estadosOrdenCompra.add("2");
        estadosOrdenCompra.add("3");
        estadosOrdenCompra.add("4");
        estadosOrdenCompra.add("5");
        estadosOrdenCompra.add("6");
        estadosOrdenCompra.add("7");
        estadosOrdenCompra.add("8");
        estadosOrdenCompra.add("20");
        
        String ESTADO[][]=estado.estadoOperacion(estadosOrdenCompra);
        
        
        
        estadosCombo = new String[ESTADO.length];
        for(int i=0;i<estadosCombo.length;i++){
            estadosCombo[i]=ESTADO[i][1];
        }
        
        
        
        
        estadoDeGestion.setModel(new DefaultComboBoxModel(estadosCombo)  );
        
        estadoCMB.setModel(new DefaultComboBoxModel(estadosCombo)  );
        
        
        
        String insumos[][]= catalogo.listaPorTipoCatalogo(19);
        
        String Insumos[]=new String[insumos.length];
        
        for(int i=0;i<Insumos.length;i++){
            Insumos[i]=insumos[i][1];
        }
        
        CMBinsumos1.setModel(new DefaultComboBoxModel(Insumos)  );
        CMBinsumos2.setModel(new DefaultComboBoxModel(Insumos)  );
        
        CMBcentroDeCostoINICIAL.setModel(new DefaultComboBoxModel(CentrosDeCosto)  );
        CMBcentroDeCostoFINAL.setModel(new DefaultComboBoxModel(CentrosDeCosto)  );
        CMBcentrosDeCostoEstadistico1.setModel(new DefaultComboBoxModel(CentrosDeCosto)  );
        CMBcentrosDeCostoEstadistico2.setModel(new DefaultComboBoxModel(CentrosDeCosto)  );
        
    
    
        
        
        
        
        String LUGARES[][]= catalogo.listaPorTipoCatalogo(22);
        String Columnas[]=new String[2];
        
        Columnas[0]="ID";
        Columnas[1]="Lugar";
        
        pendientesLugarTBL.setModel(new DefaultTableModel(LUGARES, Columnas));
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        pendientesLugarTBL = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        CALinicial = new com.toedter.calendar.JCalendar();
        CALfinal = new com.toedter.calendar.JCalendar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        CMBcentroDeCostoINICIAL = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CMBcentroDeCostoFINAL = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        estadoDeGestion = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        CMBcentrosDeCostoEstadistico1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CMBcentrosDeCostoEstadistico2 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        CMBinsumos1 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        CMBinsumos2 = new javax.swing.JComboBox<>();
        anioCAL = new com.toedter.calendar.JYearChooser();
        jLabel10 = new javax.swing.JLabel();
        estadoCMB = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel11.setText("Ver todos los Pendientes");

        jButton4.setText("Ver todos los pendientes");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel17.setText("Ver pendientes por lugar");

        pendientesLugarTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(pendientesLugarTBL);

        jButton5.setText("Ver Pendientes");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Ver Aprobados");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Ver Liquidados");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel17))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton7))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(249, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel3);

        jTabbedPane1.addTab("Vista Rapida", jScrollPane2);

        jLabel1.setText("Rango de Fechas");

        jLabel2.setText("Inicial");

        jLabel3.setText("Final");

        jLabel4.setText("Centros de Costo");

        jButton1.setText("Procesar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        CMBcentroDeCostoINICIAL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Inicial");

        jLabel6.setText("Final");

        CMBcentroDeCostoFINAL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel16.setText("Estado de la Gestión");

        estadoDeGestion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(CMBcentroDeCostoINICIAL, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CALinicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel16))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CALfinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(23, 23, 23)
                                .addComponent(CMBcentroDeCostoFINAL, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(estadoDeGestion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CALfinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CALinicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(estadoDeGestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CMBcentroDeCostoINICIAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CMBcentroDeCostoFINAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Analisis de Compra", jPanel1);

        CMBcentrosDeCostoEstadistico1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Inicial");

        jLabel8.setText("Final");

        CMBcentrosDeCostoEstadistico2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setText("Rango de Fechas");

        jLabel12.setText("Centros de Costo");

        jButton2.setText("Procesar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel13.setText("Insumos");

        jButton3.setText("Procesar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        CMBinsumos1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel14.setText("Inicial");

        jLabel15.setText("Final");

        CMBinsumos2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel10.setText("Estado de la Gestión");

        estadoCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(CMBcentrosDeCostoEstadistico2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel13)
                                    .addComponent(anioCAL, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(CMBcentrosDeCostoEstadistico1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(CMBinsumos1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(23, 23, 23)
                                .addComponent(CMBinsumos2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel10)
                    .addComponent(estadoCMB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(anioCAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(estadoCMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CMBcentrosDeCostoEstadistico1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CMBcentrosDeCostoEstadistico2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(11, 11, 11)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CMBinsumos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CMBinsumos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(187, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        jTabbedPane1.addTab("Reporte Estadistico", jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
      
        
        Reportes reporte=new Reportes();
        
        System.out.println("centroDeCostoInicial "+CMBcentroDeCostoINICIAL.getSelectedItem());
        System.out.println("centroDeCostoFinal "+CMBcentroDeCostoFINAL.getSelectedItem());
        System.out.println("anio "+utilidadesbasicas.utilidadVinculoBD.dateToString_guion(  CALinicial.getDate()  ));
        System.out.println("estado "+estadoDeGestion.getSelectedItem());
    
        
        reporte.addParametro("centroDeCostoInicial",  CMBcentroDeCostoINICIAL.getSelectedItem()+""   );
        reporte.addParametro("centroDeCostoFinal",   CMBcentroDeCostoFINAL.getSelectedItem()+""  );
        
        
        reporte.addParametro("fechaInicial",  utilidadesbasicas.utilidadVinculoBD.dateToString_guion(  CALinicial.getDate()  )+ " 00:00:00"  );
     
        reporte.addParametro("fechaFinal",  utilidadesbasicas.utilidadVinculoBD.dateToString_guion(  CALfinal.getDate()  )+ " 00:00:00"    );
        reporte.addParametro("estado",  estadoDeGestion.getSelectedItem()+""  );
       
         
        archivoProperties A=new archivoProperties("reportParams.properties");
        reporte.setImageReportDir(A.getProperties("IMAGEREPORTDIR"));
        reporte.setSubreportDir(A.getProperties("SUBREPORTDIR")+"\\reporteGeneral\\");
        reporte.verReporte("reportes\\reporteGeneral\\analisisPorInsumos.jasper", ManejadorDeDatos.BD.getCon());
        
        
        
        
            
          
            
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        

        
        
        Reportes reporte=new Reportes();
        
        reporte.addParametro("centroDeCostoInicial",  CMBcentrosDeCostoEstadistico1.getSelectedItem()+""   );
        reporte.addParametro("centroDeCostoFinal",   CMBcentrosDeCostoEstadistico2.getSelectedItem()+""  );
        

        
        reporte.addParametro("anio",  anioCAL.getYear()+""   );
        reporte.addParametro("estado",  estadoCMB.getSelectedItem()+""  );
        archivoProperties A=new archivoProperties("reportParams.properties");
        reporte.setImageReportDir(A.getProperties("IMAGEREPORTDIR"));
        reporte.setSubreportDir(A.getProperties("SUBREPORTDIR")+"\\reporteGeneral\\");
        reporte.verReporte("reportes\\reporteGeneral\\analisisPorCENTRODECOSTO.jasper", ManejadorDeDatos.BD.getCon());
        
            
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        
        Reportes reporte=new Reportes();
        
        
        
        System.out.println( "centroDeCostoInicial  "+  CMBinsumos1.getSelectedItem()  );
        System.out.println( "centroDeCostoFinal  "+  CMBinsumos2.getSelectedItem()   );
        System.out.println( "anio  "+  anioCAL.getYear()   );
        System.out.println( "estado  "+   estadoCMB.getSelectedItem()   );

        
        
        reporte.addParametro("centroDeCostoInicial",  CMBinsumos1.getSelectedItem()+""   );
        reporte.addParametro("centroDeCostoFinal",   CMBinsumos2.getSelectedItem()+""  );
        reporte.addParametro("anio",  anioCAL.getYear()+""   );
        reporte.addParametro("estado",  estadoCMB.getSelectedItem()+""  );
        
        
        archivoProperties A=new archivoProperties("reportParams.properties");
        reporte.setImageReportDir(A.getProperties("IMAGEREPORTDIR"));
        reporte.setSubreportDir(A.getProperties("SUBREPORTDIR")+"\\reporteGeneral\\");
        reporte.verReporte("reportes\\reporteGeneral\\analisisPorINSUMO.jasper", ManejadorDeDatos.BD.getCon());
        
            
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
           

            catalogo_servicio catalogo=new catalogo_servicio();
            String CAT[][]= catalogo.listaPorTipoCatalogo(20);
            

            Calendar cal= Calendar.getInstance();
            int year= cal.get(Calendar.YEAR);

            Reportes reporte=new Reportes();




            reporte.addParametro("centroDeCostoInicial",  CAT[0][1]   );
            reporte.addParametro("centroDeCostoFinal",   CAT[CAT.length-1][1]  );
            reporte.addParametro("fechaInicial",  year+"-01-01 00:00:00"  );
            reporte.addParametro("fechaFinal",  year+"-12-31 00:00:00"    );
            
            
            reporte.addParametro("anio",  year+""   );
            reporte.addParametro("estado",  "Solicitud|En proceso"  );
        
            archivoProperties A=new archivoProperties("reportParams.properties");
            reporte.setImageReportDir(A.getProperties("IMAGEREPORTDIR"));
            reporte.setSubreportDir(A.getProperties("SUBREPORTDIR")+"\\reporteGeneral\\");
            reporte.verReporte("reportes\\reporteGeneral\\analisisPorInsumos.jasper", ManejadorDeDatos.BD.getCon());

      
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
                
        if (pendientesLugarTBL.getSelectedRow()!=-1){
            String idCatalogoLugar=(String)pendientesLugarTBL.getValueAt(pendientesLugarTBL.getSelectedRow(), 0);

            catalogo_servicio catalogo=new catalogo_servicio();
            String CAT[][]=catalogo.listaPorTipoCatalogoYRelacion(idCatalogoLugar,3);


            Calendar cal= Calendar.getInstance();
            int year= cal.get(Calendar.YEAR);

            Reportes reporte=new Reportes();



        

            reporte.addParametro("centroDeCostoInicial",  CAT[0][1]   );
            reporte.addParametro("centroDeCostoFinal",   CAT[CAT.length-1][1]  );
            reporte.addParametro("fechaInicial",  year+"-01-01 00:00:00"  );
            reporte.addParametro("fechaFinal",  year+"-12-31 00:00:00"    );
            
            
            reporte.addParametro("anio",  year+""   );
            reporte.addParametro("estado",  "Solicitud|En proceso"  );
        
            archivoProperties A=new archivoProperties("reportParams.properties");
            reporte.setImageReportDir(A.getProperties("IMAGEREPORTDIR"));
            reporte.setSubreportDir(A.getProperties("SUBREPORTDIR")+"\\reporteGeneral\\");
            reporte.verReporte("reportes\\reporteGeneral\\analisisPorInsumos.jasper", ManejadorDeDatos.BD.getCon());

        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (pendientesLugarTBL.getSelectedRow()!=-1){
            String idCatalogoLugar=(String)pendientesLugarTBL.getValueAt(pendientesLugarTBL.getSelectedRow(), 0);

            catalogo_servicio catalogo=new catalogo_servicio();
            String CAT[][]=catalogo.listaPorTipoCatalogoYRelacion(idCatalogoLugar,3);


            Calendar cal= Calendar.getInstance();
            int year= cal.get(Calendar.YEAR);

            Reportes reporte=new Reportes();




            reporte.addParametro("centroDeCostoInicial",  CAT[0][1]   );
            reporte.addParametro("centroDeCostoFinal",   CAT[CAT.length-1][1]  );
            reporte.addParametro("fechaInicial",  year+"-01-01 00:00:00"  );
            reporte.addParametro("fechaFinal",  year+"-12-31 00:00:00"    );
            
            
            reporte.addParametro("anio",  year+""   );
            reporte.addParametro("estado",  "Aprobado"  );
        
            archivoProperties A=new archivoProperties("reportParams.properties");
            reporte.setImageReportDir(A.getProperties("IMAGEREPORTDIR"));
            reporte.setSubreportDir(A.getProperties("SUBREPORTDIR")+"\\reporteGeneral\\");
            reporte.verReporte("reportes\\reporteGeneral\\analisisPorInsumos.jasper", ManejadorDeDatos.BD.getCon());

        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (pendientesLugarTBL.getSelectedRow()!=-1){
            String idCatalogoLugar=(String)pendientesLugarTBL.getValueAt(pendientesLugarTBL.getSelectedRow(), 0);

            catalogo_servicio catalogo=new catalogo_servicio();
            String CAT[][]=catalogo.listaPorTipoCatalogoYRelacion(idCatalogoLugar,3);


            Calendar cal= Calendar.getInstance();
            int year= cal.get(Calendar.YEAR);

            Reportes reporte=new Reportes();



            reporte.addParametro("centroDeCostoInicial",  CAT[0][1]   );
            reporte.addParametro("centroDeCostoFinal",   CAT[CAT.length-1][1]  );
            reporte.addParametro("fechaInicial",  year+"-01-01 00:00:00"  );
            reporte.addParametro("fechaFinal",  year+"-12-31 00:00:00"    );
            
            
            reporte.addParametro("anio",  year+""   );
            reporte.addParametro("estado",  "Aplicado"  );
        
            archivoProperties A=new archivoProperties("reportParams.properties");
            reporte.setImageReportDir(A.getProperties("IMAGEREPORTDIR"));
            reporte.setSubreportDir(A.getProperties("SUBREPORTDIR")+"\\reporteGeneral\\");
            reporte.verReporte("reportes\\reporteGeneral\\analisisPorInsumos.jasper", ManejadorDeDatos.BD.getCon());

        }
    }//GEN-LAST:event_jButton7ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JCalendar CALfinal;
    private com.toedter.calendar.JCalendar CALinicial;
    private javax.swing.JComboBox<String> CMBcentroDeCostoFINAL;
    private javax.swing.JComboBox<String> CMBcentroDeCostoINICIAL;
    private javax.swing.JComboBox<String> CMBcentrosDeCostoEstadistico1;
    private javax.swing.JComboBox<String> CMBcentrosDeCostoEstadistico2;
    private javax.swing.JComboBox<String> CMBinsumos1;
    private javax.swing.JComboBox<String> CMBinsumos2;
    private com.toedter.calendar.JYearChooser anioCAL;
    private javax.swing.JComboBox<String> estadoCMB;
    private javax.swing.JComboBox<String> estadoDeGestion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable pendientesLugarTBL;
    // End of variables declaration//GEN-END:variables
}
